### ISSUE TITLE
Half of drive motors are not working

### ISSUE THREAD

**Issue by emcauliffe** [MacRover/Rover#17]
Working motors:

- P0
- P1
- P2

Non-working motors:

- P3
- P4
- P5

PWM signal on P3 works when P4 is disabled. When only P3 and P5 are active, P3 produces a pwm signal but P5 produces nothing. Whenever P4 is active, all P3, P4, and P5 stop working.

TIM1 controls P0, P1, and P2. TIM3 is supposed to control P3, P4, and P5.

**Comment by ishanvermani** [comment]
Via the PinMap for the STM32F103C8 Black Pill (https://github.com/stm32duino/Arduino_Core_STM32/blob/76887a45b43c9e919db17df9e039d96bd01641d1/variants/STM32F1xx/F103C8T_F103CB(T-U)/PeripheralPins.c#L95), the default activity of each pin can be seen. In order to configure Pins PA7 and PB0 to TIM3, they need to be called as PA_7_ALT1 and PB_0_ALT1.

This, however, isn't recognized as an Arduino digital pin name. To correct for this, Pins A7 and B0 are defined by the STM Pin name, and the `digitalPinToPinName()` function is ignored (definition of the function is found here, with no indication of how do define the alternate function of a digital pin: https://github.com/stm32duino/Arduino_Core_STM32/blob/e156c32db24d69cb4818208ccc28894e2f427cfa/cores/arduino/pins_arduino.h#L97)
